### PR TITLE
New update version 2.1.7.1

### PR DESCRIPTION
**Pull request by iBLiSSIN**

### CODE REVIEW

**Comment by russyboy** [comment]
there is nothing in iBLiSSIN:master

**Comment by russyboy** [comment]
what do you want to do

**Comment by russyboy** [comment]
And there is no need to have 2.1.7.1 version, icehacks will release 3.0 surviv cheat soon.

**Comment by iBLiSSIN** [comment]
Soon? I know it very hard and it need a very very very very long time to do.

**Comment by dinhanhx** [comment]
> And there is no need to have 2.1.7.1 version, icehacks will release 3.0 surviv cheat soon.

I thought icehack drop support for this tool. Now we are on our all

**Comment by russyboy** [comment]
> Soon? I know it very hard and it need a very very very very long time to do.

yes of course

**Comment by russyboy** [comment]
zoom with scroll wheel is the hardest part to do in this project, the second hardest is the flashlight ok?

**Comment by IceHacks** [comment]
@russyboy none of that is hard, the problem is that I don't really ever have time to work on this.

**Comment by dinhanhx** [comment]
Let Icehacks rest and do other stuff for himself.

**Comment by russyboy** [comment]
> @russyboy none of that is hard, the problem is that I don't really ever have time to work on this.

Im so sorry

**Comment by russyboy** [comment]
> Let Icehacks rest and do other stuff for himself.

yes

**Comment by JIAJIAPNXA** [comment]
Icehacks can you first fix Aimbot 2.0 and release this?

**Comment by JIAJIAPNXA** [comment]
i mean if you do not have time to make 3.0 you can just fix 2.0,to make aimbot just working.

**Comment by dinhanhx** [comment]
> Icehacks can you first fix Aimbot 2.0 and release this?

He can but he WON'T DO. "I don't really ever have time to work on this" ~ IceHack

**Comment by iBLiSSIN** [comment]
Oh, in just a few days I did not expect IceHacks to contribute to my pull request.

**Comment by russyboy** [comment]
> Oh, in just a few days I did not expect IceHacks to contribute to my pull request.

Oof

**Comment by iBLiSSIN** [comment]
And you are online?

**Comment by dinhanhx** [comment]
> what is this request for anyway?

Maybe just for attention

**Comment by iBLiSSIN** [comment]
this request is not attention. i want share the aimbot 1.0. Please watch in here : https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/2.1.7.1 . Because the aimbot 2.0 by Humphrey gaming is very gay and  i want all hacker temporary use this aimbot until the release of SurvivCheatInjector 3.0.

**Comment by JIAJIAPNXA** [comment]
Aimbot 2.0 is broken,1.0 Works... But it slow (maybe that because i laggy)

**Comment by iBLiSSIN** [comment]
Yes it slow

**Comment by IceHacks** [comment]
@iBLiSSIN releases cannot be merged

**Comment by dinhanhx** [comment]
> this request is not attention. i want share the aimbot 1.0. Please watch in here : https://github.com/iBLiSSIN/SurvivCheatInjector/releases/tag/2.1.7.1 . Because the aimbot 2.0 by Humphrey gaming is very gay and i want all hacker temporary use this aimbot until the release of SurvivCheatInjector 3.0.

then you should have mentioned it sooner.

**Comment by iBLiSSIN** [comment]
Ha ha

**Comment by iBLiSSIN** [comment]
> @iBLiSSIN releases cannot be merged

Year so i don ‘t know how to create a pull request of the releases

**Comment by iBLiSSIN** [comment]
And IceHacks please fix spinbot of my aimbot 1.0 icehacks. Thanks:)

**Comment by iBLiSSIN** [comment]
Uhh but how to Humphrey Gaminh do ít?

**Pull request merged**
