### PR TITLE
add auto-switch for weapons when fire

### PR DESCRIPTION
**Pull request by flancast90**
- Added feature to prevent reload when in battle. 
- Allows players to continue firing when in fight without reload time

### CODE REVIEW

**Comment by lillabell** [comment]
wait is this supposed to be a pr? it seems more like an issue.

**Comment by flancast90** [comment]
> wait is this supposed to be a pr? it seems more like an issue.

Nope. I added this feature myself :wink:

**Comment by lillabell** [comment]
Cool but I can't tell what the change even is :|

**Comment by flancast90** [comment]
When you’re in a fight, generally the behavior of the guns is to reload
after it runs out of ammo, and then shoot after that. I made it so that it
auto switches weapons to not reload in the middle of a battle.

**Comment by flancast90** [comment]
So if everything’s going alright, you shouldn’t see any changes until
you’re in the middle of a fight. This behavior is only active when there is
an enemy nearby, otherwise it just reloads the current weapon as normal.

**Comment by lillabell** [comment]
👌🏾

**Pull request merged**
